### ISSUE TITLE
wrong implementation of openai embedding batchSize 

### ISSUE THREAD

**Issue by ken-wizhodl** [tmc/langchaingo#322]
Hi, 

I'm playing around with this lib and one immediate problem I found is the handle of embedding in batch.

Expected:
If I want to embedding a list of string `texts` []string, and given a `batchSize` option with the `WithBatchSize`, the expected bahavior should be as simple as send `batchSize` items in `texts` to the openai service.  

the official nodejs implementation of langchain is this, check: https://github.com/langchain-ai/langchainjs/blob/4e9e23137de8d2bc61dfbcf05e8e35a8f1e89ef5/langchain/src/embeddings/openai.ts#L153 

Current implementation:
The current implementation is treat `texts` as a long string and split it into `batchSize` length chars. 

Because the default batchSize is 512, in the current implementation, this behavior may result in sending a lot of small openai embedding requests, thus the follow issue:
https://github.com/tmc/langchaingo/issues/218

**Comment by jaylalakiya** [comment]
I think this is because of confusion between chunkSize and batchSize when implementing this (https://github.com/tmc/langchaingo/blob/213b9dca74c0049cfe0a32aaaebd1635a2baa017/embeddings/embedding.go#L76) function. This function batches the []texts by taking each text and **dividing** them into _batchSize_ chars instead of **grouping** the texts into _batchSize_ elements

If texts are ["abcd", "efgh", "ijkl", "mnop"] and batchSize is 2, current implementation breaks it into [ ["ab", "cd"], ["ef", "gh"], ... ] instead of [ ["abcd", "efgh" ], ["ijkl", "mnop"] ]

@tmc @FluffyKebab I am creating a PR for this issue according to above insights.
