### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by tmc** [tmc/langchaingo#388]
We're going to begin tagging releases once the current embeddings refactor (#379) is complete.

**Comment by eliben** [comment]
The refactoring of #379 is almost complete - and I think it's alright to tag a release.

The remaining providers are:

* tei: I added a comment on this in https://github.com/tmc/langchaingo/pull/352 - as it was just added very recently. Perhaps it can be adapted to the current interface

* huggingface: this one is a bit harder because its `LLM.CreateEmbedding` doesn't have the same signature as the other providers. @tmc you did some work on the huggingface provider, WDYT? Can it be refactored to present the same interface? The model can be chosen when the client is created, I don't know if people really expect to call `CreateEmbedding` on the same client with different models

**Comment by tmc** [comment]
thanks @eliben, I had missed that comment. We went ahead and got v0.1.0 out but will push a new release once this refactor is complete. Closing this for now.
