### ISSUE TITLE
googleai options need add default value by chain call

### ISSUE THREAD

**Issue by Abirdcfly** [tmc/langchaingo#626]
Test code

```go
func TestLLMChainWithGoogleAI(t *testing.T) {
	t.Parallel()
	genaiKey := os.Getenv("GENAI_API_KEY")
	if genaiKey == "" {
		t.Skip("GENAI_API_KEY not set")
	}
	model, err := googleai.New(context.Background(), googleai.WithAPIKey(genaiKey))
	require.NoError(t, err)
	require.NoError(t, err)
	model.CallbacksHandler = callbacks.LogHandler{}

	prompt := prompts.NewPromptTemplate(
		"What is the capital of {{.country}}",
		[]string{"country"},
	)
	require.NoError(t, err)

	chain := NewLLMChain(model, prompt)

	result, err := Predict(context.Background(), chain,
		map[string]any{
			"country": "France",
		},
		WithCallback(callbacks.LogHandler{}),
	)
	require.NoError(t, err)
	require.True(t, strings.Contains(result, "Paris"))
}
```

Let me explain what happened:
When calling `llm` via `chain`, because it goes through the function： https://github.com/tmc/langchaingo/blob/853fc0492d2331518252a357759546abfb1f9fea/chains/options.go#L132-L158 

Before this function, only a certain `ChainCallOption` may have been called, but after this function, it will return the 11 l`lms.CallOptions` that are currently available (although some of them are with empty value in there), so the empty value need to be dealt with at the `llm` level.

I'm **guessing** that openai's handler is in the
https://github.com/tmc/langchaingo/blob/853fc0492d2331518252a357759546abfb1f9fea/llms/openai/internal/openaiclient/completions.go#L49-L70

**Comment by eliben** [comment]
> 
> Let me explain what happened: When calling `llm` via `chain`, because it goes through the function：
> 
> https://github.com/tmc/langchaingo/blob/853fc0492d2331518252a357759546abfb1f9fea/chains/options.go#L132-L158
> 

This doesn't seem right to me, because it means that no option is left on its default value when going through a chain. This is really problematic, because different backends may have different defaults.

I wonder why the chain needs to force-initialize all options like this; maybe that's where the root of the problem is.

**Comment by eliben** [comment]
@FluffyKebab @tmc why do we have `chains/options.go` which duplicates most things in `llms/options.go`?

A serious problem with this approach is that `getLLMCallOptions` in `chains/options.go` hard-sets all the options on the call, not distinguishing between what the user actually changed from default and what they didn't.

**Comment by Abirdcfly** [comment]
Some duplicate reports:
#604
#603

**Comment by eliben** [comment]
@Abirdcfly thanks for finding these.

PTAL at #632 which is a backwards-compatible fix that makes sure to only override call options when they were explicitly set on chain options.

I think the real solution would be to get rid of `chainCallOption` altogether, since they just duplicate `llms.CallOptions`, and use the latters in chains where necessary. This will simplify a lot of code and prevent this class of bugs entirely. Thoughts?

**Comment by eliben** [comment]
This isn't done yet. We want to reconsider the duplication of options in chains

**Comment by tmc** [comment]
Quite supportive of collapsing / simplifying these.
